# Use postgres/example user/password credentials
version: "3.1"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  rcli:
    image: redis:latest
    links:
      - redis
    command: redis-cli -h redis
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
