# Use postgres/example user/password credentials
version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  rcli:
    image: redis:latest
    links:
      - redis
    command: redis-cli -h redis
  mongo:
    image: mongo:6.0.1-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/sphere/coding/price-discovery-ws/data:/data/db
